config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root "landing#index"
  get :about, to: 'static_pages#about'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :body, length: { minimum: 20 }, presence: true
  has_many :votes

  def total_votes
    votes.pluck(:value).sum
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @post = Post.includes(:comments).friendly.find(params[:post_id])
    @topic = @post.topic
    @comments = @post.comments.order("created_at DESC").page(params[:page]).per(5)
    @comment = Comment.new
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @topic = @post.topic
    @comment = current_user.comments.build(comment_params.merge(post_id: @post.id))
    @new_comment = Comment.new

    if @comment.save
      CommentBroadcastJob.perform_later("create", @comment)
      flash.now[:success] = "You've created a new comment."
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def edit
   @post = Post.friendly.find(params[:post_id])
   @topic = @post.topic
   @comment = Comment.find_by(id: params[:id])
   authorize @comment
 end

  def update
  
    @post = Post.friendly.find(params[:post_id])

    @topic = @post.topic
    @comment = Comment.find_by(id: params[:id])
    @comment_updated = false
    authorize @comment

    if @comment.update(comment_params)
      @comment_updated = true
      CommentBroadcastJob.perform_now("update", @comment)
      flash.now[:success] = "You've updated your comment."

    else
      flash.now[:danger] = @comment.errors.full_messages

    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    @topic = @comment.post.topic
    authorize @comment

    if @comment.destroy
      CommentBroadcastJob.perform_now("destroy", @comment)
      flash.now[:success] = "You've deleted the comment."
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body, :image)
  end

end

app/views/comments/_comment.html.erb
<div class="flex-child comment" data-id="<%=comment.id%>">
  <% if comment.image? %>
    <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
  <% end %>

  <h5><%= comment.body %></h5>

  <div class="control-panel">
    <% if comment.user == current_user || current_user&.admin? || current_user&.moderator? %>
      <%= link_to ("Edit"), edit_topic_post_comment_path(post.topic, post, comment), remote: true, class: "btn btn-warning" %>
      <%= link_to ("Delete"), topic_post_comment_path(post.topic, post, comment), remote: true, method: :delete, data: { confirm: "Delete?" }, :class => "btn btn-warning" %>
    <% end %>
  </div>

  <div class="vote-buttons">
    Score: <%= comment.total_votes %>
    Date: <%= comment.created_at.strftime("%B %d, %Y") %>
    User: <%= comment.user.username %>
    <% if comment.user.image? %>
    Userpic: <%= image_tag comment.user.image.url %>
    
    <% end %>

    <%= link_to ("Upvote"), upvote_path({comment_id: comment.id}), method: :post, remote: true, class: "fa fa-thumbs-o-up" %>
    <%= link_to ("Downvote"), downvote_path({comment_id: comment.id}), method: :post, remote: true, class: "fa fa-thumbs-o-down" %>
  </div>
</div>

app/views/comments/_create_form.html.erb
<div id="comment-form-container">
<%= form_for(comment, url: topic_post_comments_path(post.topic, post), method: :post, authenticity_token: true, remote: true, html: { id: "comment-create-form", multipart: true }) do |f| %>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if comment.image? %>
          <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %> -->
  </div>

  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
</div>

app/views/comments/_edit_form.html.erb
<div class="form-edit">
  <div id="comment-update">

    <%= form_for(comment, url: topic_post_comment_path(topic, post, comment), authenticity_token: true, remote: true, html: { id: "comment-update-form", multipart: true }) do |f| %>

      <% if comment.image? %>
        <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    

      <div class="form-group">
        <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :text_field, "Body" %> </h4>
        <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit class: "btn btn-success btn-lg" %>
        <div class="btn btn-success btn-lg cancel-button" data-id="<%= @comment.id %>">
          Cancel here lah
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment.persisted? %>
  $('#comment-form-container').html("<%=j render partial: 'create_form', locals: { comment: @new_comment, post: @post } %>")
<% end %>

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('.comment[data-id=<%=@comment.id%>]').remove()("<%=j render partial: 'comment', locals: { comment: @comment, post: @comment.post, topic: @topic } %>")

app/views/comments/edit.js.erb
console.log($('.comment[data-id=<%=@comment.id%>]'))

$('.comment[data-id=<%=@comment.id%>]').html("<%=j render partial: 'edit_form', locals: { comment: @comment, post: @post, topic: @topic } %>")
$('.cancel-button').on('click', function() {
  $('.comment[data-id=<%=@comment.id%>]').after("<%=j render partial: 'comments/comment', locals: { comment: @comment, post: @comment.post } %>").remove()
})

app/views/comments/index.html.erb
<div class="comments index" data-id="<%=@post.id%>">

  <div class="background_comments">
    <h1>Comments</h1>
  </div>

  <div class="flex-parent text-center">
    <div id="comments">
      <% @comments.each do |comment| %>
        <%= render partial: "comment", locals: { comment: comment, post: @post, topic: @topic } %>
      <% end %>
    </div>
  </div>

  <!-- <div class="new_comment_button">
    <%= link_to ("Add New Comment"), new_topic_post_comment_path, :class => "btn btn-warning" %>
  </div> -->

  <div id="comments-form-container">
    <%= render partial: "create_form", locals: { comment: @comment, post: @post } %>
  </div>

  <%= paginate @comments %>

</div>

app/views/comments/new.html.erb
<div class="comments">
  <div class="flex-parent text-center">
    <div class="flex-child">

<%= form_for(@comment, url: topic_post_comments_path(@topic, @post), html: { id: "comment-create-form" }) do |f| %>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @comment.image? %>
          <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>
  
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment_updated %>
  $('.comment[data-id=<%=@comment.id%>]').replaceWith("<%=j render partial: 'comment', locals: { comment: @comment, post: @comment.post, topic: @topic } %>");
<% end %>

// data-id, or you can append it to the id #comment-55