config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root "landing#index"
  get :about, to: 'static_pages#about'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :topic
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  extend FriendlyId
  friendly_id :title, use: :slugged

  before_save :update_slug

  def update_slug
    if title
      self.slug = title.gsub(" ", "-")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @topic = Topic.includes(:posts).friendly.find(params[:topic_id])
    @posts = @topic.posts.order("created_at DESC").page(params[:page]).per(5)
    @post = Post.new
  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])

    @post = current_user.posts.build(post_params.merge(topic_id: @topic.id))
    # @post = current_user.posts.build(post_params)
    # @post.topic_id = @topic.id
    @new_post = Post.new

    if @post.save
      flash.now[:success] = "You've created a new post."
    else
      flash.now[:danger] = @post.errors.full_messages
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic_id
    authorize @post
  end

  def update
    @post = Post.friendly.find(params[:id])
    @topic = Topic.friendly.find(params[:topic_id])
    authorize @post
    if @post.update(post_params)
      flash[:success] = "You've updated the post."
      redirect_to topic_posts_path(@topic)
    else
      flash[:danger] = @post.errors.full_messages
      redirect_to edit_topic_post_path(@topic, @post)
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post
    if @post.destroy
      flash[:success] = "You've deleted the post."
      redirect_to topic_posts_path(@topic)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/views/posts/_create_form.html.erb
<%= form_for(post, url: topic_posts_path(topic), method: :post, authenticity_token: true, remote: true, html: { id: "post-create-form", multipart: true }) do |f| %>
  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if post.image? %>
          <%= image_tag post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "body_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="flex-child">
    <% if post.image? %>
      <%= image_tag post.image, class: "img-settings img-responsive center-block" %>
    <% end %>
    
  <h3><%= link_to post.title, topic_post_comments_path(@topic, post), :class => "title-link-color" %></h3>
  <h5><%= post.body %></h5>
  <%= link_to ("Edit"), edit_topic_post_path(@topic, post), :class => "btn btn-warning" %>
  <%= link_to ("Delete"), topic_post_path(@topic, post), method: :delete, data: { confirm: "Delete?" }, :class => "btn btn-warning" %>
</div>

app/views/posts/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @post.persisted? %>
  $('#posts').prepend("<%=j render partial: 'posts', locals: { post: @post, topic: @post.topic } %>")
  $('#posts-form-container').html("<%=j render partial: 'create_form', locals: { post: @new_post, topic: @topic } %>")
<% end %>

app/views/posts/edit.html.erb
<div class="topics">
  <div class="flex-parent text-center">
    <div class="flex-child">

<%= form_for(@post, url: topic_post_path(@topic, @post), html: { id: "post-update-form" }) do |f| %>

    <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if @post.image? %>
        <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>

  <h1 class="text-center">
    Edit Post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="posts">

  <div class="background_posts">
    <h1><%="#{@topic.title}"%></h1>
  </div>

  <div class="background2_posts">
    <div style="padding:15px">

      <div class="flex-parent text-center">
        <div id="posts">
        <% @posts.each do |post| %>
          <%= render partial: "posts", locals: { post: post, topic: @topic } %>
        <% end %>
        </div>
      </div>

    </div>
  </div>

    <!-- <div style="padding-bottom:15px">
      <div class="new_post_button">
        <%= link_to ("Add New Post"), new_topic_post_path, :class => "btn btn-warning" %>
      </div>
    </div> -->
  <div id="posts-form-container">
    <%= render partial: "create_form", locals: { post: @post, topic: @topic } %>
  </div>

  <%= paginate @posts %> 
</div>

app/views/posts/new.html.erb
<div class="topics">
  <div class="flex-parent text-center">
    <div class="flex-child">

<%= form_for(@post, url: topic_posts_path(@topic), html: { id: "post-create-form" }) do |f| %>
  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @post.image? %>
          <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "body_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>